### ISSUE TITLE
Adding parameters to basic getter/setter methods "feel wrong"

### ISSUE THREAD

**Issue by rickclare** [jonpearse/will_translate#1]
Hi JP, I thought I'd offer some (hopefully constructive) criticism:

To me, altering the fundamental getter & setter methods of ActiveRecord models seems wrong - breaks some basic OO principal.  These getters and setters should be as simple as possible, thats's what a developer would expect when using ActiveRecord models (just like other simple OO objects)

Could you adapt the code just to use the current I18n.locale value (usual practice is to assign the value of I18n.locale at the start of each request in an ApplicationController before filtering). See the following code example for what I'm driving at. 
https://github.com/globalize/globalize#model-translations

**Comment by rickclare** [comment]
... actually I think my main worry is that the parameter is not explicit enough and therefore open to misunderstanding, misuse or conflict with other gems and patches.

This could be solved by using a "named parameters" instead

```
model.title(locale: :en)
model.title = { :locales => { :fr => "Hello world in French" } }
```

Being more explicit also means that other gems that alter ActiveRecord getters won't conflict with your gem and also future-proofs your implementation.

With Ruby 2 this is even easier to implement (I.e. "Named parameters" are "keyword arguments")
http://ruby.about.com/od/beginningruby/ss/Keyword-Arguments.htm

**Comment by jonpearse** [comment]
Hey,

The code already supports the functionality you describe, thus:

``` Ruby
I18n.locale = :en
t = MyModel.new :title => "Hello"

I18n.locale = :fr
t.title = "Bonjour"
t.title
# => "Bonjour"

I18n.locale = :en
t.title
# => "Hello"
```

Your point about the explicitness of the parameters is a very good one. If I’m honest, I threw the gem together to scratch a very particular itch, and without thinking too much about the wider world. Will update the getter forthwith.

Thanks for the feedback—much appreciated!
J

**Comment by rickclare** [comment]
Happy to help (as you know, I'm always up for sticking my oar in!)

Next step - you could write some test specs for your gem - then it really would be ready for the wider world! All good practice and all that!
